# 上传通道 线路A1 线路A2 线路A3 自定义
uploader: "线路A1"
# 上传并发
upload_task: 10
# 上传失败重试
upload_retry: 10
#下载并发
download_task: 5
# 端口
port: 4719
host: "0.0.0.0"
# 自定义线路url
custom_url: ""
#自定义线路referer
custom_referer: ""
